name: ZAP Security Scan

on:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Baseline Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'https://reqres.in'
